function buildTagsIndex() {
  // index[tag][groupName] = ["Outfit1", "Outfit2", ...]
  const index = {};
  outfits.forEach(o => {
    const tags = (o.data.tags || '').trim().split(/\s+/).filter(Boolean);
    const gn = groupName(o);
    tags.forEach(tag => {
      if (!index[tag]) index[tag] = {};
      if (!index[tag][gn]) index[tag][gn] = [];
      index[tag][gn].push(o.name);
    });
  });
  if (!Object.keys(index).length) return '';
  // One self-contained escaped JSON object per line, one tag per line
  const tags = Object.keys(index).sort();
  const lines = tags.map(tag => {
    const groupObj = {};
    Object.keys(index[tag]).sort().forEach(gn => {
      groupObj[gn] = index[tag][gn].join('··');
    });
    return JSON.stringify({ [tag]: groupObj });
  });
  return lines.join('\n');
}

function generateAll() {
  saveActiveEditor();
  if (!outfits.length && !groups.length) { notify(t('no_outfits')); return; }

  const header =
`// ══════════════════════════════════════════════════════════════════════════════
// SUBBI CLOTHES - OUTFIT SETTINGS CONFIGURATION
// Generated by Subbi Outfit Config Editor
// ══════════════════════════════════════════════════════════════════════════════\n\n`;

  const colorKeys = Object.keys(tagColors);
  const colorSuffix = colorKeys.length ? '\n\n// SUBBI_OCE_COLORS: ' + JSON.stringify(tagColors) : '';
  const tagsIndex = buildTagsIndex();
  const tagsSuffix = tagsIndex ? '\n\n// === TAGS INDEX ===\n' + tagsIndex : '';

  const tagsByGroup = {};
  outfits.forEach(o => {
    const tags = (o.data.tags || '').trim().split(/\s+/).filter(Boolean);
    if (!tags.length) return;
    const gn = groupName(o);
    if (!tagsByGroup[gn]) tagsByGroup[gn] = new Set();
    tags.forEach(tag => tagsByGroup[gn].add(tag));
  });
  const allTagsSuffix = Object.keys(tagsByGroup).length
    ? '\n\n' + Object.keys(tagsByGroup).sort().map(gn =>
        JSON.stringify({ ['tags-' + gn]: [...tagsByGroup[gn]].sort().join(',') })
      ).join('\n')
    : '';

  // Group Tags — an independent category for the HUD (not part of the
  // Default/Group/Outfit settings cascade), so it's exported separately
  // from the per-outfit tags aggregate above.
  const groupTagLines = groups
    .filter(g => g.groupTags && g.groupTags.trim())
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(g => JSON.stringify({ ['group-tags-' + g.name]: g.groupTags.trim().split(/\s+/).join(',') }));
  const groupTagsSuffix = groupTagLines.length ? '\n\n' + groupTagLines.join('\n') : '';

  // Favorites — a top-level flag on the outfit, not a field inside its
  // settings block, so it's exported as its own independent line (same
  // treatment as Group Tags above).
  const favKeys = outfits.filter(o => o.favorite).map(o => `${groupName(o)}/${o.name}`).sort();
  const favoritesSuffix = favKeys.length ? '\n\n' + JSON.stringify({ favorites: favKeys.join(',') }) : '';

  // Each group's settings block, immediately followed by its outfits.
  const sortedGroups = [...groups].sort((a, b) => a.name.localeCompare(b.name));
  const blocks = [];
  sortedGroups.forEach(g => {
    blocks.push(groupToString(g));
    outfits.filter(o => o.groupId === g.id).forEach(o => blocks.push(outfitToString(o)));
  });
  // Defensive: outfits whose group no longer exists shouldn't occur post-migration, but don't drop them silently.
  outfits.filter(o => !groups.some(g => g.id === o.groupId)).forEach(o => blocks.push(outfitToString(o)));

  document.getElementById('outputCode').value = header + blocks.join('\n\n') + colorSuffix + tagsSuffix + allTagsSuffix + groupTagsSuffix + favoritesSuffix;
  document.getElementById('instrList').innerHTML = (INSTR[lang] || INSTR.en).map(fn => `<li>${fn()}</li>`).join('');
  openModal('outputModal');
}

// Shared serializer for both an outfit's settings block and a group's
// settings block — same field set and cascade shape, only the export key
// and whether the (outfit-only) tags line is included differ.
function serializeSettingsBlock(key, d, opts) {
  opts = opts || {};
  const lines = [];
  const pushBool = (k, v) => { if (v !== null && v !== undefined) lines.push(`    "${k}": ${v},`); };
  lines.push(`"${key}": {`);
  if (d.gender && d.gender !== 'Auto') lines.push(`    "gender": "${d.gender}",`);
  pushBool('animations_enabled',   d.animations_enabled);
  pushBool('skelfix_change',       d.skelfix_change);
  pushBool('skelfix_reload',       d.skelfix_reload);
  pushBool('nudity_permission',    d.nudity_permission);
  pushBool('hairstyle_permission', d.hairstyle_permission);
  pushBool('clothes_permission',   d.clothes_permission);
  pushBool('lock_ankles',          d.lock_ankles);
  if (d.pg_safe_mode) lines.push(`    "pg_safe_mode": "${d.pg_safe_mode}",`);
  if (opts.tags && d.tags && d.tags.trim()) lines.push(`    "tags": "${d.tags.trim().replace(/"/g, '')}",`);
  lines.push('');

  const enabled = BODY_PARTS.filter(p => d.bodyparts[p] && d.bodyparts[p].enabled);
  if (enabled.length) {
    const sv = (v, fb) => v || fb || '';
    const nv = (v, fb) => (v === '' || isNaN(+v)) ? Number(fb ?? 1.0).toFixed(1) : Number(v).toFixed(1);
    enabled.forEach(p => {
      const bp  = d.bodyparts[p];
      const def = BP_DEFAULTS[p] || {};
      lines.push(`    "${p}": { "normal": "${sv(bp.normal, def.normal)}", "underwear": "${sv(bp.underwear, def.underwear)}", "wear_anim": "${sv(bp.wear_anim, def.wear_anim)}", "wear_time": ${nv(bp.wear_time, def.wear_time)}, "remove_anim": "${sv(bp.remove_anim, def.remove_anim)}", "remove_time": ${nv(bp.remove_time, def.remove_time)} },`);
    });
    lines.push('');
  }

  pushBool('particles_enabled', d.particles_enabled);
  if (d.particles_texture) lines.push(`    "particles_texture": "${d.particles_texture}",`);
  if (d.particles_duration !== null && d.particles_duration !== undefined && d.particles_duration !== '') {
    lines.push(`    "particles_duration": ${Number(d.particles_duration).toFixed(1)},`);
  }
  if (d.particles_color_start_enabled || d.particles_color_end_enabled) {
    const colStart = encodeColorForOutput(d.particles_color_start || '<1.0, 1.0, 1.0>');
    const colEnd   = encodeColorForOutput(d.particles_color_end   || '<1.0, 1.0, 1.0>');
    if (d.particles_color_start_enabled && d.particles_color_end_enabled) {
      lines.push(`    "particles_color": "${colStart}:${colEnd}",`);
    } else {
      lines.push(`    "particles_color": "${d.particles_color_start_enabled ? colStart : colEnd}",`);
    }
  }
  if (d.particles_radius      != null) lines.push(`    "particles_radius": ${Number(d.particles_radius).toFixed(2)},`);
  if (d.particles_alpha_start != null) lines.push(`    "particles_alpha_start": ${Number(d.particles_alpha_start).toFixed(2)},`);
  if (d.particles_alpha_end   != null) lines.push(`    "particles_alpha_end": ${Number(d.particles_alpha_end).toFixed(2)},`);
  if (d.particles_glow_start  != null) lines.push(`    "particles_glow_start": ${parseFloat((Number(d.particles_glow_start) * 0.01).toFixed(4))},`);
  if (d.particles_glow_end    != null) lines.push(`    "particles_glow_end": ${parseFloat((Number(d.particles_glow_end) * 0.01).toFixed(4))},`);
  if (d.particles_size_start  != null) lines.push(`    "particles_size_start": ${Number(d.particles_size_start).toFixed(2)},`);
  if (d.particles_size_end    != null) lines.push(`    "particles_size_end": ${Number(d.particles_size_end).toFixed(2)},`);
  lines.push('');
  pushBool('title_enabled', d.title_enabled);
  if (d.title_text) lines.push(`    "title_text": "${encodeTitleText(d.title_text, d.title_mode, d.title_scroll_size).replace(/\n/g, '\\n')}",`);
  if (d.title_color_enabled) lines.push(`    "title_color": "${encodeColorForOutput(d.title_color)}",`);
  if (d.biography) lines.push(`    "biography": "${d.biography.replace(/\n/g, '\\n')}",`);
  lines.push('');
  lines.push('// === END OUTFIT ===');
  return lines.join('\n');
}

function outfitToString(o) {
  return serializeSettingsBlock(`${groupName(o)}/${o.name}`, o.data, { tags: true });
}

function groupToString(g) {
  return serializeSettingsBlock(`${g.name}/*`, g.data, { tags: false });
}

function copyOutfitConfig(id) {
  saveActiveEditor();
  const o = outfits.find(x => x.id === id);
  if (!o) return;
  navigator.clipboard.writeText(outfitToString(o))
    .then(() => notify(t('outfit_copied')));
}

function copyGroupConfig(id) {
  saveActiveEditor();
  const g = groups.find(x => x.id === id);
  if (!g) return;
  navigator.clipboard.writeText(groupToString(g))
    .then(() => notify(t('outfit_copied')));
}

/* ── PASTE CONFIG ──
   Inverse of copyOutfitConfig/copyGroupConfig: read a copied settings block and
   merge a chosen subset of its categories into the current outfit or group. */

// Which data fields belong to each pasteable category. `bodyparts` is deep-copied
// separately since it's a nested object.
const PASTE_CATEGORY_FIELDS = {
  settings:  ['gender','animations_enabled','skelfix_change','skelfix_reload',
              'nudity_permission','hairstyle_permission','clothes_permission',
              'lock_ankles','pg_safe_mode'],
  tags:      ['tags'],
  particles: ['particles_enabled','particles_texture','particles_duration',
              'particles_color_start_enabled','particles_color_end_enabled',
              'particles_color_start','particles_color_end','particles_radius',
              'particles_alpha_start','particles_alpha_end','particles_glow_start',
              'particles_glow_end','particles_size_start','particles_size_end'],
  title:     ['title_enabled','title_text','title_mode','title_scroll_size',
              'title_color_enabled','title_color'],
  biography: ['biography'],
};

// Parse the first settings block found in `text` into a DEFAULT_OUTFIT()-shaped
// object (reusing the importer's helpers). Returns null if nothing parseable.
function parseSingleBlockToData(text) {
  const lines = String(text || '').split('\n');
  const blockRegex = /^\s*"([^"]+\/[^"]+)"\s*:\s*\{/;
  let blockLines = null, inBlock = false;
  for (const line of lines) {
    if (!inBlock) {
      if (blockRegex.test(line)) { blockLines = ['{']; inBlock = true; }
    } else {
      if (line.includes('// === END OUTFIT ===')) break;
      const stripped = line.replace(/\/\/.*$/, '').trimEnd();
      if (stripped.trim()) blockLines.push(stripped);
    }
  }
  if (!blockLines) return null;
  blockLines.push('}');
  try {
    const obj = JSON.parse(fixBlockJson(blockLines.join('\n')));
    const d = DEFAULT_OUTFIT();
    parseSettingsBlock(obj, d);
    if (obj.tags !== undefined) d.tags = obj.tags;
    return d;
  } catch (e) { return null; }
}

function applyCategories(dst, src, cats) {
  cats.forEach(cat => {
    if (cat === 'bodyparts') { dst.bodyparts = JSON.parse(JSON.stringify(src.bodyparts)); return; }
    (PASTE_CATEGORY_FIELDS[cat] || []).forEach(f => { dst[f] = src[f]; });
  });
}

function openPasteConfigModal(id, mode) {
  pasteTargetId = id;
  pasteTargetMode = mode;
  document.getElementById('pasteConfigArea').value = '';
  const cats = [
    { key: 'settings',  label: t('sec_settings')  },
    { key: 'tags',      label: t('sec_tags')      },
    { key: 'bodyparts', label: t('sec_bodyparts') },
    { key: 'particles', label: t('sec_particles') },
    { key: 'title',     label: t('sec_title')     },
    { key: 'biography', label: t('sec_biography') },
  ].filter(c => !(c.key === 'tags' && mode === 'group')); // groups carry no outfit tags

  const rows = cats.map(c =>
    `<label class="paste-cat"><input type="checkbox" class="paste-cat-chk" value="${c.key}" checked onchange="syncPasteAll()"><span>${esc(c.label)}</span></label>`
  ).join('');
  document.getElementById('pasteCatList').innerHTML =
    `<label class="paste-cat paste-cat-all"><input type="checkbox" id="pasteCatAll" checked onchange="togglePasteAll(this)"><span>${t('paste_all')}</span></label>` +
    `<div class="paste-cat-grid">${rows}</div>`;
  openModal('pasteConfigModal');
  setTimeout(() => document.getElementById('pasteConfigArea').focus(), 100);
}

function togglePasteAll(master) {
  document.querySelectorAll('.paste-cat-chk').forEach(chk => { chk.checked = master.checked; });
}

function syncPasteAll() {
  const all = [...document.querySelectorAll('.paste-cat-chk')];
  document.getElementById('pasteCatAll').checked = all.every(c => c.checked);
}

function confirmPasteConfig() {
  const text = document.getElementById('pasteConfigArea').value;
  if (!text.trim()) return;
  const parsed = parseSingleBlockToData(text);
  if (!parsed) { notify(t('paste_invalid'), 'warning'); return; }
  const selected = [...document.querySelectorAll('.paste-cat-chk:checked')].map(c => c.value);
  if (!selected.length) { notify(t('paste_none'), 'warning'); return; }

  const target = pasteTargetMode === 'group'
    ? groups.find(g => g.id === pasteTargetId)
    : outfits.find(o => o.id === pasteTargetId);
  if (!target) return;

  saveActiveEditor();
  applyCategories(target.data, parsed, selected);
  closeModal('pasteConfigModal');
  if (pasteTargetMode === 'group') renderGroupEditor(target.id);
  else renderEditor(target.id);
  renderSidebar();
  notify(t('paste_applied'));
  saveToStorage();
}

function copyOutput() {
  navigator.clipboard.writeText(document.getElementById('outputCode').value)
    .then(() => notify(t('copied')));
}

function downloadOutput() {
  const blob = new Blob([document.getElementById('outputCode').value], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'outfits_settings.json';
  a.click();
}
