function buildTagsIndex() {
  // index[tag][groupName] = ["Outfit1", "Outfit2", ...]
  const index = {};
  outfits.forEach(o => {
    const tags = (o.data.tags || '').trim().split(/\s+/).filter(Boolean);
    const gn = groupName(o);
    tags.forEach(tag => {
      if (!index[tag]) index[tag] = {};
      if (!index[tag][gn]) index[tag][gn] = [];
      index[tag][gn].push(o.name);
    });
  });
  if (!Object.keys(index).length) return '';
  // One self-contained escaped JSON object per line, one tag per line
  const tags = Object.keys(index).sort();
  const lines = tags.map(tag => {
    const groupObj = {};
    Object.keys(index[tag]).sort().forEach(gn => {
      groupObj[gn] = index[tag][gn].join('··');
    });
    return JSON.stringify({ [tag]: groupObj });
  });
  return lines.join('\n');
}

function generateAll() {
  saveActiveEditor();
  if (!outfits.length && !groups.length) { notify(t('no_outfits')); return; }

  const header =
`// ══════════════════════════════════════════════════════════════════════════════
// SUBBI CLOTHES - OUTFIT SETTINGS CONFIGURATION
// Generated by Subbi Outfit Config Editor
// ══════════════════════════════════════════════════════════════════════════════\n\n`;

  const colorKeys = Object.keys(tagColors);
  const colorSuffix = colorKeys.length ? '\n\n// SUBBI_OCE_COLORS: ' + JSON.stringify(tagColors) : '';
  const tagsIndex = buildTagsIndex();
  const tagsSuffix = tagsIndex ? '\n\n// === TAGS INDEX ===\n' + tagsIndex : '';

  const tagsByGroup = {};
  outfits.forEach(o => {
    const tags = (o.data.tags || '').trim().split(/\s+/).filter(Boolean);
    if (!tags.length) return;
    const gn = groupName(o);
    if (!tagsByGroup[gn]) tagsByGroup[gn] = new Set();
    tags.forEach(tag => tagsByGroup[gn].add(tag));
  });
  const allTagsSuffix = Object.keys(tagsByGroup).length
    ? '\n\n' + Object.keys(tagsByGroup).sort().map(gn =>
        JSON.stringify({ ['tags-' + gn]: [...tagsByGroup[gn]].sort().join(',') })
      ).join('\n')
    : '';

  // Group Tags — an independent category for the HUD (not part of the
  // Default/Group/Outfit settings cascade), so it's exported separately
  // from the per-outfit tags aggregate above.
  const groupTagLines = groups
    .filter(g => g.groupTags && g.groupTags.trim())
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(g => JSON.stringify({ ['group-tags-' + g.name]: g.groupTags.trim().split(/\s+/).join(',') }));
  const groupTagsSuffix = groupTagLines.length ? '\n\n' + groupTagLines.join('\n') : '';

  // Each group's settings block, immediately followed by its outfits.
  const sortedGroups = [...groups].sort((a, b) => a.name.localeCompare(b.name));
  const blocks = [];
  sortedGroups.forEach(g => {
    blocks.push(groupToString(g));
    outfits.filter(o => o.groupId === g.id).forEach(o => blocks.push(outfitToString(o)));
  });
  // Defensive: outfits whose group no longer exists shouldn't occur post-migration, but don't drop them silently.
  outfits.filter(o => !groups.some(g => g.id === o.groupId)).forEach(o => blocks.push(outfitToString(o)));

  document.getElementById('outputCode').value = header + blocks.join('\n\n') + colorSuffix + tagsSuffix + allTagsSuffix + groupTagsSuffix;
  document.getElementById('instrList').innerHTML = (INSTR[lang] || INSTR.en).map(fn => `<li>${fn()}</li>`).join('');
  openModal('outputModal');
}

// Shared serializer for both an outfit's settings block and a group's
// settings block — same field set and cascade shape, only the export key
// and whether the (outfit-only) tags line is included differ.
function serializeSettingsBlock(key, d, opts) {
  opts = opts || {};
  const lines = [];
  const pushBool = (k, v) => { if (v !== null && v !== undefined) lines.push(`    "${k}": ${v},`); };
  lines.push(`"${key}": {`);
  if (d.gender && d.gender !== 'Auto') lines.push(`    "gender": "${d.gender}",`);
  pushBool('animations_enabled',   d.animations_enabled);
  pushBool('skelfix_change',       d.skelfix_change);
  pushBool('skelfix_reload',       d.skelfix_reload);
  pushBool('nudity_permission',    d.nudity_permission);
  pushBool('hairstyle_permission', d.hairstyle_permission);
  pushBool('clothes_permission',   d.clothes_permission);
  pushBool('lock_ankles',          d.lock_ankles);
  if (d.pg_safe_mode) lines.push(`    "pg_safe_mode": "${d.pg_safe_mode}",`);
  if (opts.tags && d.tags && d.tags.trim()) lines.push(`    "tags": "${d.tags.trim().replace(/"/g, '')}",`);
  lines.push('');

  const enabled = BODY_PARTS.filter(p => d.bodyparts[p] && d.bodyparts[p].enabled);
  if (enabled.length) {
    const sv = (v, fb) => v || fb || '';
    const nv = (v, fb) => (v === '' || isNaN(+v)) ? Number(fb ?? 1.0).toFixed(1) : Number(v).toFixed(1);
    enabled.forEach(p => {
      const bp  = d.bodyparts[p];
      const def = BP_DEFAULTS[p] || {};
      lines.push(`    "${p}": { "normal": "${sv(bp.normal, def.normal)}", "underwear": "${sv(bp.underwear, def.underwear)}", "wear_anim": "${sv(bp.wear_anim, def.wear_anim)}", "wear_time": ${nv(bp.wear_time, def.wear_time)}, "remove_anim": "${sv(bp.remove_anim, def.remove_anim)}", "remove_time": ${nv(bp.remove_time, def.remove_time)} },`);
    });
    lines.push('');
  }

  pushBool('particles_enabled', d.particles_enabled);
  if (d.particles_texture) lines.push(`    "particles_texture": "${d.particles_texture}",`);
  if (d.particles_duration !== null && d.particles_duration !== undefined && d.particles_duration !== '') {
    lines.push(`    "particles_duration": ${Number(d.particles_duration).toFixed(1)},`);
  }
  if (d.particles_color_start_enabled || d.particles_color_end_enabled) {
    const colStart = encodeColorForOutput(d.particles_color_start || '<1.0, 1.0, 1.0>');
    const colEnd   = encodeColorForOutput(d.particles_color_end   || '<1.0, 1.0, 1.0>');
    if (d.particles_color_start_enabled && d.particles_color_end_enabled) {
      lines.push(`    "particles_color": "${colStart}:${colEnd}",`);
    } else {
      lines.push(`    "particles_color": "${d.particles_color_start_enabled ? colStart : colEnd}",`);
    }
  }
  if (d.particles_radius      != null) lines.push(`    "particles_radius": ${Number(d.particles_radius).toFixed(2)},`);
  if (d.particles_alpha_start != null) lines.push(`    "particles_alpha_start": ${Number(d.particles_alpha_start).toFixed(2)},`);
  if (d.particles_alpha_end   != null) lines.push(`    "particles_alpha_end": ${Number(d.particles_alpha_end).toFixed(2)},`);
  if (d.particles_glow_start  != null) lines.push(`    "particles_glow_start": ${parseFloat((Number(d.particles_glow_start) * 0.01).toFixed(4))},`);
  if (d.particles_glow_end    != null) lines.push(`    "particles_glow_end": ${parseFloat((Number(d.particles_glow_end) * 0.01).toFixed(4))},`);
  if (d.particles_size_start  != null) lines.push(`    "particles_size_start": ${Number(d.particles_size_start).toFixed(2)},`);
  if (d.particles_size_end    != null) lines.push(`    "particles_size_end": ${Number(d.particles_size_end).toFixed(2)},`);
  lines.push('');
  pushBool('title_enabled', d.title_enabled);
  if (d.title_text) lines.push(`    "title_text": "${encodeTitleText(d.title_text, d.title_mode, d.title_scroll_size).replace(/\n/g, '\\n')}",`);
  if (d.title_color_enabled) lines.push(`    "title_color": "${encodeColorForOutput(d.title_color)}",`);
  if (d.biography) lines.push(`    "biography": "${d.biography.replace(/\n/g, '\\n')}",`);
  lines.push('');
  lines.push('// === END OUTFIT ===');
  return lines.join('\n');
}

function outfitToString(o) {
  return serializeSettingsBlock(`${groupName(o)}/${o.name}`, o.data, { tags: true });
}

function groupToString(g) {
  return serializeSettingsBlock(`${g.name}/*`, g.data, { tags: false });
}

function copyOutfitConfig(id) {
  saveActiveEditor();
  const o = outfits.find(x => x.id === id);
  if (!o) return;
  navigator.clipboard.writeText(outfitToString(o))
    .then(() => notify(t('outfit_copied')));
}

function copyGroupConfig(id) {
  saveActiveEditor();
  const g = groups.find(x => x.id === id);
  if (!g) return;
  navigator.clipboard.writeText(groupToString(g))
    .then(() => notify(t('outfit_copied')));
}

function copyOutput() {
  navigator.clipboard.writeText(document.getElementById('outputCode').value)
    .then(() => notify(t('copied')));
}

function downloadOutput() {
  const blob = new Blob([document.getElementById('outputCode').value], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'outfits_settings.json';
  a.click();
}
