function generateAll() {
  saveActiveEditor();
  if (!outfits.length) { notify(t('no_outfits')); return; }

  const header =
`// ══════════════════════════════════════════════════════════════════════════════
// SUBBI CLOTHES - OUTFIT SETTINGS CONFIGURATION
// Generated by Subbi Outfit Config Editor
// ══════════════════════════════════════════════════════════════════════════════\n\n`;

  document.getElementById('outputCode').value = header + outfits.map(outfitToString).join('\n\n');
  document.getElementById('instrList').innerHTML = (INSTR[lang] || INSTR.en).map(fn => `<li>${fn()}</li>`).join('');
  openModal('outputModal');
}

function outfitToString(o) {
  const d = o.data;
  const key = `"${o.avatar}/${o.name}"`;
  const lines = [];
  const pushBool = (k, v) => { if (v !== null && v !== undefined) lines.push(`    "${k}": ${v},`); };
  lines.push(`${key}: {`);
  if (d.gender && d.gender !== 'Auto') lines.push(`    "gender": "${d.gender}",`);
  pushBool('animations_enabled',   d.animations_enabled);
  pushBool('skelfix_change',       d.skelfix_change);
  pushBool('skelfix_reload',       d.skelfix_reload);
  pushBool('nudity_permission',    d.nudity_permission);
  pushBool('hairstyle_permission', d.hairstyle_permission);
  pushBool('clothes_permission',   d.clothes_permission);
  pushBool('lock_ankles',          d.lock_ankles);
  if (d.pg_safe_mode) lines.push(`    "pg_safe_mode": "${d.pg_safe_mode}",`);
  lines.push('');

  const enabled = BODY_PARTS.filter(p => d.bodyparts[p] && d.bodyparts[p].enabled);
  if (enabled.length) {
    const sv = (v, fb) => v || fb || '';
    const nv = (v, fb) => (v === '' || isNaN(+v)) ? Number(fb ?? 1.0).toFixed(1) : Number(v).toFixed(1);
    enabled.forEach(p => {
      const bp  = d.bodyparts[p];
      const def = BP_DEFAULTS[p] || {};
      lines.push(`    "${p}": { "normal": "${sv(bp.normal, def.normal)}", "underwear": "${sv(bp.underwear, def.underwear)}", "wear_anim": "${sv(bp.wear_anim, def.wear_anim)}", "wear_time": ${nv(bp.wear_time, def.wear_time)}, "remove_anim": "${sv(bp.remove_anim, def.remove_anim)}", "remove_time": ${nv(bp.remove_time, def.remove_time)} },`);
    });
    lines.push('');
  }

  const colStart = d.particles_color_start || '<1.0, 1.0, 1.0>';
  const colEnd   = d.particles_color_end   || '<1.0, 1.0, 1.0>';
  pushBool('particles_enabled', d.particles_enabled);
  lines.push(`    "particles_texture": "${d.particles_texture}",`);
  lines.push(`    "particles_duration": ${(d.particles_duration || 0).toFixed(1)},`);
  lines.push(`    "particles_color": "${colStart}:${colEnd}",`);
  lines.push('');
  pushBool('title_enabled', d.title_enabled);
  lines.push(`    "title_text": "${d.title_text}",`);
  lines.push(`    "title_color": "${d.title_color}"`);
  lines.push('');
  lines.push('// === END OUTFIT ===');
  return lines.join('\n');
}

function copyOutput() {
  navigator.clipboard.writeText(document.getElementById('outputCode').value)
    .then(() => notify(t('copied')));
}

function downloadOutput() {
  const blob = new Blob([document.getElementById('outputCode').value], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'outfits_settings.json';
  a.click();
}
